[tool.poetry]
name = "gesture-recognition"
version = "0.1.0"
description = "SlideCaster controller driven by gesture recognition"
authors = ["Dessera <1533653159@qq.com>"]
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
mediapipe = "^0.10.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
